config/routes.rb
Rails.application.routes.draw do
  
  resources :posts
  resources :admin
  devise_for :users
root to: "home#index"
get 'home/about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many_attached:images
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_one_attached :avatar
         has_many :posts
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @users= User.all
    @posts= Post.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

     before_action :configure_permitted_parameters, if: :devise_controller?

     protected

          def configure_permitted_parameters
               devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:firstname,:lastname,:username,:avatar,:email,:password,:acc_type,:remember_me)}

               devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:firstname,:lastname,:username,:avatar,:email,:password,:acc_type, :current_password)}
          end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users=User.where(acc_type:"public")
    @posts=Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:show, :index]
  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, images:[])
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    # def sign_up_params
    #     params.require(:user).permit(:firstname,:lastname,:username,:avatar,:email,:password,:password_confirmation)
    # end
    # def edit
    # end
    # def update
    #     User.update(sign_up_params)
    #     if User.update(sign_up_params)
    #         redirect_to root_path
    #     end
    # end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/admin/index.html.erb
<center><h1>Admin Page</h1></center>
<h2>Users</h2>
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Firstname</th>
      <th scope="col">Lastname</th>
      <th scope="col">Username</th>
      <th scope="col">Avatar</th>
      <th scope="col">AccountType</th>
      <th scope="col">Email</th>
      
      
    </tr>
  </thead>
<tbody>
<% @users.each do |user| %>
    <tr>
    <td><%= user.id %></td>
    <td><%= user.firstname %></td>
    <td><%= user.lastname %></td>
    <td><%= user.username %></td>
    <td><%= image_tag user.avatar, width:'30px' %></td>
    <td><%= user.acc_type %></td>
    <td><%= user.email %></td>
    
   
    </tr>
    
    <% end %>
    </tbody>
    </table>
    <br/>
    <h2>User's posts</h2>
    <table class="table table-bordered">
  <thead>
    <tr>
      
      <th scope="col">User Name</th>
      <th scope="col">Title</th>  
      <th scope="col">Body</th>
      <th scope="col">Images</th>
      
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
        <tr>
        <td><%= post.user.username %></td>
       <td> <%= post.title %></td>
       <td> <%= post.body %></td>
       <td><% post.images.each do |image| %>
        <%= image_tag image, width:"30px" %>
            <% end %></td>
       </tr>
        <% end %>
        </tbody>
        </table>

app/views/home/about.html.erb
<center><h1>About Instabook</h1></center>
<br/>
<p style="font-size:35px"><strong>Instabook</strong> is the webapplication we can create a new account here...
Once created a new account we can create a new posts..... <br/>
<i>For New Registeration</i> </p>
<b><%= link_to "click here", new_user_registration_path %></b>

app/views/home/index.html.erb
<style>
hr{
    height: 2px;
    background-color: #ff0000;
    border: none;
}
</style>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<% if current_user.present? %>

<h1> Welcome, <%= current_user.firstname %>&nbsp;<%= current_user.lastname %> </h1><br/>
<%= link_to "Edit profile" , edit_user_registration_path %><br/><br/>
<%if current_user.avatar.persisted? %><%= image_tag current_user.avatar,width:'80px' %><% end %><br/>
<br/>
<%= link_to "Create Posts" , posts_path %> 

<% else %>
<h1> Welcome to Instabook </h1><br/>

<% @users.each do |user|%>
    <div class="text-center">
    <p><%= image_tag user.avatar, width:'30px' %> &nbsp;User Name: <%= user.firstname %> <%= user.lastname %></p>
    
    <% @posts.each do |post| %>
        <% if user.id==post.user.id %>
        <% post.images.each do |image| %>    
                    
            <%= image_tag image, width:'200px' %>
            <% end %>
        <p>Title:<%= post.title %></p>
        <p>Body:<%= post.body %></p>
        <hr>
         <%end %>
        <% end %>
        
        <%end %>
        
        </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  
    <title>Instabook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  <%= render 'shared/navbar' %>
  
  <div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <style>
    .navbar-nav{
      
    }
  .form-control
  {
    width:50%
    
  }
  </style>
    </div>
    
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title,class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body,class:'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :images %>
    <%= form.file_field :images,multiple:true,class:'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
     
      <th>Images</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
      <% if current_user.id == post.user_id %>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><% post.images.each do |image| %>
          
          <%= image_tag image, width:"30px" %>
          <% end %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %> &nbsp; <%= link_to 'Back', root_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.email.split('@')[0].capitalize %>
</p>
<p>
  <strong>Images:</strong>
  <% if @post.images.attached? %>
  <% @post.images.each do |image| %>
    <%= image_tag image, width:"200px" %>
    <% end %>
  <% end %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-info">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">Instabook</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
      <li class="nav-item">
      <%= link_to 'Home', root_path, class:'nav-link' %>
       </li>
       <li class="nav-item">
       <%= link_to 'About', home_about_path, class:'nav-link' %>
        </li>
        <% if controller_name != "admin" %>
      <% if user_signed_in? %>
      <li class="nav-item">
      <%= link_to 'Logout', destroy_user_session_path, method: :delete, class:'nav-link' %>
       </li>
      
       
       <% else %>
       <li class="nav-item">
       <%= link_to 'Register', new_user_registration_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
        <%= link_to 'Login', new_user_session_path, class:'nav-link' %>
         </li>
         
        <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>